name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
      runs-on: ubunto-latest
      steps:
        - run: echo "Obter o código"
        - run: echo "Executar o Docker Build"
        - run: echo "Enviar a Imagem Docke para o Docker Hub"
  CD:
      runs-on: ubunto-latest
      needs: [CI]
      steps:
        - run: echo "Obter o código"
        - run: echo "Configurar o Kubeconnfig"
        - run: echo "Executar o apply"

  
        
